import { createFileRoute } from "@tanstack/react-router";
import { ShieldCheck, Info, Lock, AlertTriangle, Users } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { PageHeader } from "@/components/module-shell";

export const Route = createFileRoute("/_app/responsible-ai")({
  head: () => ({ meta: [{ title: "Responsible AI — WorkPilot" }] }),
  component: ResponsibleAI,
});

const items = [
  {
    icon: Info,
    title: "AI can make mistakes",
    body: "Outputs are generated by a large language model and may contain inaccuracies, omissions, or out-of-date information. Always review before sending, sharing, or acting on results.",
  },
  {
    icon: Users,
    title: "You are responsible",
    body: "You remain accountable for what you send and decide. Treat WorkPilot as a draft assistant, not a decision-maker. Apply your own judgment, ethics, and domain expertise.",
  },
  {
    icon: Lock,
    title: "Mind sensitive data",
    body: "Avoid pasting passwords, secrets, personal data of others, or confidential information unless your organization has approved it. Inputs are sent to a third-party AI provider for processing.",
  },
  {
    icon: AlertTriangle,
    title: "Not professional advice",
    body: "WorkPilot does not provide legal, medical, financial, HR, or compliance advice. Consult qualified professionals for those domains.",
  },
];

function ResponsibleAI() {
  return (
    <div className="mx-auto max-w-4xl">
      <PageHeader
        icon={<ShieldCheck className="h-5 w-5" />}
        title="Responsible AI"
        description="How to use WorkPilot well — and what to keep in mind."
      />

      <div className="grid gap-4 sm:grid-cols-2">
        {items.map((it) => (
          <Card key={it.title}>
            <CardHeader>
              <div className="mb-2 grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary">
                <it.icon className="h-4 w-4" />
              </div>
              <CardTitle className="text-base">{it.title}</CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-muted-foreground">{it.body}</CardContent>
          </Card>
        ))}
      </div>

      <Card className="mt-6">
        <CardHeader>
          <CardTitle className="text-base">How your data is handled</CardTitle>
          <CardDescription>App-owner statement</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3 text-sm text-muted-foreground">
          <p>
            Your generated outputs and saved history for the productivity modules live in your
            browser's local storage. Clearing your browser data removes them. They are not synced or
            stored on a server by this app.
          </p>
          <p>
            Your inputs (e.g. emails, notes, prompts) are transmitted to an AI provider via the
            Lovable AI Gateway to generate responses. Do not include confidential information unless
            your organization has approved this use.
          </p>
          <p>
            This page is maintained by the app owner. It describes current behavior of this build
            and is not a certification or audit.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
